# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatabaseGateway < Formula
  desc "Safe access to production databases"
  homepage "https://github.com/kazhuravlev/database-gateway"
  version "0.13.13"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kazhuravlev/database-gateway/releases/download/v0.13.13/database-gateway_darwin_arm64.tar.gz"
      sha256 "ab0c01886bd93e835a105ccb97123867bbc24a61ad5f3ff21d12e672f4b0d138"

      def install
        bin.install "database-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kazhuravlev/database-gateway/releases/download/v0.13.13/database-gateway_linux_arm64.tar.gz"
        sha256 "2d993e3792b8a7e4ce21553f1c88e1d5c80a0100f4d7820667d1dcf8019ad205"

        def install
          bin.install "database-gateway"
        end
      end
    end
  end

  test do
    system "#{bin}/gateway help"
  end
end
