# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatabaseGateway < Formula
  desc "Safe access to production databases"
  homepage "https://github.com/kazhuravlev/database-gateway"
  version "0.13.14"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kazhuravlev/database-gateway/releases/download/v0.13.14/database-gateway_darwin_arm64.tar.gz"
      sha256 "bda17e0305bf4f93c92b8f9934f5fb89854552d03a18dc57badcacec99ed5295"

      def install
        bin.install "database-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kazhuravlev/database-gateway/releases/download/v0.13.14/database-gateway_linux_arm64.tar.gz"
        sha256 "37027e777dce45575d514f695a9a2b038a186a5d6548bc5e095d99359fd9b6e0"

        def install
          bin.install "database-gateway"
        end
      end
    end
  end

  test do
    system "#{bin}/gateway help"
  end
end
