# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatabaseGateway < Formula
  desc "Safe access to production databases"
  homepage "https://github.com/kazhuravlev/database-gateway"
  version "0.13.12"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kazhuravlev/database-gateway/releases/download/v0.13.12/database-gateway_darwin_arm64.tar.gz"
      sha256 "894ce9eb0b14884de8727a3f6212345842127326712217d131bf8a30b27842b9"

      def install
        bin.install "database-gateway"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/kazhuravlev/database-gateway/releases/download/v0.13.12/database-gateway_linux_arm64.tar.gz"
        sha256 "d2c838ec997d35ef0b703dc1eb9f70c45273627720b20e91d003f4ec8ee14ffe"

        def install
          bin.install "database-gateway"
        end
      end
    end
  end

  test do
    system "#{bin}/gateway help"
  end
end
